### ISSUE TITLE
PdfFileReader deprecation exception in PdfReader class

### ISSUE THREAD

**Issue by richbai90** [colemana/PyPDF2#16]
I'm trying to pdf page from a file-like BytesIO object using the PdfReader class because PdfFileReader is deprecated, and it continues to throw the PdfFileReader deprecation error. I found the line causing the error and it is in the PdfReader class. I'm not sure if I'm missing something basic but I'm confused why the deprecation exception would show up in the PdfReader class.

## My Code
```python
    packet = io.BytesIO()
    packet.write(bytes("test string", "utf-8"))
    # Move to the beginning of the StringIO buffer
    packet.seek(0)
    return PdfReader(packet) # Raises exception
```

## Exception
```
ERROR:root:Traceback (most recent call last):
  File "/home/rich/Documents/school/menon/code/scrape_grants/scrape_personal.py", line 105, in main
    preamble = create_preamble()
  File "/home/rich/Documents/school/menon/code/scrape_grants/scrape_personal.py", line 74, in create_preamble
    return PdfReader(packet)
  File "/home/rich/mambaforge/envs/scrape/lib/python3.10/site-packages/PyPDF2/_reader.py", line 1974, in __init__
    deprecation_with_replacement("PdfFileReader", "PdfReader", "3.0.0")
  File "/home/rich/mambaforge/envs/scrape/lib/python3.10/site-packages/PyPDF2/_utils.py", line 369, in deprecation_with_replacement
    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))
  File "/home/rich/mambaforge/envs/scrape/lib/python3.10/site-packages/PyPDF2/_utils.py", line 351, in deprecation
    raise DeprecationError(msg)
PyPDF2.errors.DeprecationError: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.
```
## Relevant section of library code
```python
class PdfReader(PdfReader):  # pragma: no cover
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        deprecation_with_replacement("PdfFileReader", "PdfReader", "3.0.0")
        if "strict" not in kwargs and len(args) < 2:
            kwargs["strict"] = True  # maintain the default
        super().__init__(*args, **kwargs)
```

**Comment by richbai90** [comment]
Wrong repo. Also it was a corruption on my end.
