### ISSUE TITLE
error: Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by neofyte** [colemana/PyPDF2#5]
I am porting my script from python27 to python33.
When I run the code `pdf = PdfFileReader(open('xxxx.pdf', 'rb'))`, the error message appears:

```
Traceback (most recent call last):
File ..., in <module>raw_content = pdf.getPage(0).extractText()
File "C:\Python33\lib\site-packages\PyPDF2\pdf.py", line 1718, in extract Textcontent = ContentStream(content, self.pdf)
File "C:\Python33\lib\site-packages\PyPDF2\pdf.py", line 1797, in __init__data += s.getObject().getData()
TypeError: Can't convert 'bytes' object to str implicitly
```

On the other hand, I cannot open the file with 

```
pdf = PdfFileReader(open('xxxx.pdf', 'r'))
```

otherwise, it comes the following messages:

```
io.UnsupportedOperation: can't do nonzero end-relative seeks
```

What's going wrong?

**Comment by juankysmith** [comment]
I am having the same problem :( Have you found any solution?

**Comment by jdkanani** [comment]
Same problem :(

**Comment by james-see** [comment]
According to docs you can't seek the end of a file without the beginning for python 3.2+. I am having the same issue.

**Comment by beigi** [comment]
same problem
